config/routes.rb
Discovery::Application.routes.draw do
  
  devise_for :empleados
  resources :paquete
  resources :horarios
  resources :recibo
  resources :terminal
  resources :ruta
  resources :cliente
  resources :verrecibos
  resources :verempleados
  resources :verclientes
  
  get 'verclientes/index'
  get 'verrecibos/index'
  get 'verempleados/index'
  get 'cliente/index'
  get 'ruta/index'
  get 'terminal/index'
  get 'main/index'
  get 'horarios/index'
  get 'paquete/index'
  get 'recibo/index'
  root 'main#index'
  

end

app/models/bus.rb
class Bus < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :empleado  
  has_many :caminos
 def validate
     unless Empleado.find_by_id(empleado_id)
       errors.add(:empleado_id, 'does not exist')
     end
   end # validate
    
    
end

app/models/camino.rb
class Camino < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :terminal
  belongs_to :bus
  has_many :recibos
  
 def validate
     unless Terminal.find_by_id(terminal_id_origen)
       errors.add(:terminal_id_origen, 'does not exist')
     end
     unless Terminal.find_by_id(terminal_id_destino)
       errors.add(:terminal_id_destino, 'does not exist')
     end
   end # validate
  
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :recibos
  has_many :paquetes
  

 
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  belongs_to :terminal
  has_one :bus
  has_many :recibos
  
  def validate
     unless Terminal.find_by_id(terminal_id)
       errors.add(:terminal_id, 'does not exist')
     end
   end
  
  
end

    
      

app/models/paquete.rb
class Paquete < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :recibo
  belongs_to :cliente
  def validate
     unless Recibo.find_by_id(recibo_id)
       errors.add(:recibo_id, 'does not exist')
     end
   end

end

app/models/recibo.rb
class Recibo < ActiveRecord::Base
  belongs_to :empleado
  belongs_to :cliente
  has_one :paquete
  has_one :camino

  validates :fecha_de_viaje, presence: true
 
end

app/models/ruta.rb
class Ruta < ActiveRecord::Base
  belongs_to :terminal
  belongs_to :bus
  has_one :recibo
end

app/models/terminal.rb
class Terminal < ActiveRecord::Base
   has_many :empleados
   has_many :caminos
end

app/controllers/main_controller.rb
class MainController < ApplicationController  
  def index
      #redirect_to :controller=>'login'
  end
end

app/controllers/recibo_controller.rb
class ReciboController < ApplicationController
 
  def index
    @recibo = Recibo.new
    @camino = Camino.all 
    @i= 1
    @j= 0
    @asientos= Array.new  
    while @i < 49
      @asientos[@j] = @i
       @i += 1
      @j += 1
    end
  end
  
  def create 
    @recibo = Recibo.create(recibo_params)
    
    @fecha_viaje = Recibo.find_by_fecha_de_viaje(params[:fecha_de_viaje])
    @ruta = Recibo.find_by_camino_id(params[:camino_id] )  
    
   if @recibo.save
     redirect_to :controller=>'main'
   end
  end
  
   private
  
  def recibo_params
    # params.require(:user) throws an error if params[:user] is nil
    params.require(:recibo).permit( :empleado_id, :cliente_id, :camino_id, :fecha_de_viaje, :tipo, :asiento)
 end
  
  
  
end

app/controllers/ruta_controller.rb
class RutaController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  
  def is_active?(link_path)
  if current_page?(link_path)
    "active"
  else
    ""
  end
 end
  
  
  
  
end

app/helpers/cliente_helper.rb
module ClienteHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/paquete_helper.rb
module PaqueteHelper
end

app/helpers/recibo_helper.rb
module ReciboHelper
  
  
  def is_Available?
    
    Recibo.all.each do |t|
     
      if t.asiento?(1)
        "Available"
      else
        "NotAvailable"
      end
    end
    
  end
  
end

app/helpers/ruta_helper.rb
module RutaHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/terminal_helper.rb
module TerminalHelper
end

app/helpers/verclientes_helper.rb
module VerclientesHelper
end

app/helpers/verrecibos_helper.rb
module VerrecibosHelper
end

app/views/recibo/index.html.erb
      <!-- --------------------------------------empezamos a programar el bolento------------------------------------------------- -->
    <br>
      <h1>e-Ticket</h1>  
    <br>
  <div class="container marketing">
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="span4">
           <h1>Horarios</h1>
          <br>
             <table  border="1" cellpadding="1" cellspacing="1" class="table table-condensed">
            <tr>
              <th>id</th>
              <th>Origen</th>
              <th>Destino</th>
              <th>Horario sale</th>
              <th>Horario LLe.</th>
            </tr>          
            <% @camino.each do |u| %>
              <tr> 
                <td><%= u.id %> </td>
                <td><%= Terminal.find_by_id(u.terminal_id_origen).nombre %> </td>
                <td><%= Terminal.find_by_id(u.terminal_id_destino).nombre %> </td>
                <td>sale <%= u.hora_salida.strftime("%H:%M") %></td>
                <td>lle. <%= u.hora_llegada.strftime("%H:%M") %></td>
               </tr>
            <% end %>                    
          </table>                
          </div>
        <div class="span4"> 
           <%= form_for @recibo, :url => { :action => "create" } do |t| %>
           
          <div><%= t.label :'Horarios Id' %>                  
            <%= t.collection_select(:camino_id ,Camino.all, :id, :id) %><br /> </div> 
           <% if empleado_signed_in? %>   
          
          <div> <%= t.label :'empleado_id' %>                  
            <%= t.email_field :email,  value: Empleado.find_by_email(current_empleado.email).email %></div>
         <% end %>          
       
          <div><%= t.label :'cliente_id' %>   <i>(si su id no existe porfavor crear uno)</i>  <%= link_to 'agregar cliente', new_cliente_path %>
           <%= t.collection_select(:cliente_id ,Cliente.all, :id, :id) %><br /></div> 
          
          <div><%= t.label :'fecha_de_viaje' %>                  
            <%= t.date_field :'fecha_de_viaje', :start_year => 1950  %> <br/> </div> 
         
          <% if empleado_signed_in? %>              
            <div> <%= t.label :'tipo' %>                  
              <%= t.select :'tipo', options_for_select([ "Normal", "Paquete"], "Normal" ) %><br /></div> 
          
          <% end %>
         <%= t.label :'asiento' %> 
          <%= t.select :'asiento', options_for_select(@asientos) ,  :action => :index %>
          <br/>
          <br/>
            <%= t.submit "Agregar" %>
        <% end %>  
        </div> 
        <div class="span4">
           <h1 margin-right: 35%;>Acientos</h1> 
            <div class="holder">
              <div class="InnerGrid">
                <table cellspacing="0" id="content_GridMapa" style="border-collapse:collapse; margin-left: 35%;"  >
                  <tr>
                    <br><br><br><br><br><br><tr>
                    <td><input type="button" value="01" class="Available" name="recibo[asiento]"></td>
                    <td><input type="button" value="02" class="Available" name="recibo[asiento]"></td>
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td><input type="button" value="03" class="Available"   name="recibo[asiento]"/></td>
                    <td><input type="button"value="04"  class="Available"   name="recibo[asiento]"/></td>
                   </tr>
                  <tr>
                    <td><input type="button" value="05"  class="Available"  name="recibo[asiento]"></td>
                    <td><input type="button" value="06" class="Available"></td>
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td><input type="button"   name="recibo[asiento]" value="07" class="Available"></td>
                    <td><input type="button"  name="recibo[asiento]" value="08" class="Available"></td>
                  </tr>                           
                  <tr>
                    <td><input type="button" name="recibo[asiento]" value="09" class="Available"></td>
                    <td><input type="button" name="recibo[asiento]" value="10" class="Available"></td>
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td><input type="button"  name="recibo[asiento]" value="11" class="Available"></td>
                    <td><input type="button"  name="recibo[asiento]" value="12" class="Available"></td>
                  </tr>
                  <tr>
                    <td><input type="button" name="recibo[asiento]" value="13" class="Available"></td>
                    <td><input type="button" name="recibo[asiento]" value="14" class="Available"></td>
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td><input type="button" name="recibo[asiento]" value="15" class="Available"></td>
                    <td><input type="button" name="recibo[asiento]"  value="16" class="Available"></td>
                  </tr>
                  <tr>
                    <td><input type="button" name="recibo[asiento]" value="17" class="Available"></td>
                    <td><input type="button" name="recibo[asiento]" value="18" class="Available"></td>
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td></td>
                    <td></td>
                  </tr>
                  <tr>
                    <td><input type="button" value="21" class="Available"></td>
                    <td><input type="button" value="22" class="Available"></td>
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td></td>
                    <td></td>
                  </tr>
                  <tr>
                    <td><input type="button" name="recibo[asiento]" value="25" class="Available"></td>
                    <td><input type="button" name="recibo[asiento]" value="26" class="Available"></td>
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td><input type="button" name="recibo[asiento]" value="19" class="Available"></td>
                    <td><input type="button" name="ctl00$content$GridMapa$ctl07$Button4" value="20" id="content_GridMapa_Button4_5" class="Available" />
                    </td>
                  </tr>
                  <tr>
                    <td><input type="button" name="recibo[asiento]" value="29" id="" class="Available"></td>
                    <td> <input type="button" name="recibo[asiento]" value="30" id="" class="Available"></td> 
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td><input type="button" name="recibo[asiento]" value="23" id="" class="Available"></td>
                    <td> <input type="button" name="recibo[asiento]" value="24" id="" class="Available" /></td>
                  </tr>
                  <tr>
                    <td><input type="button" name="recibo[asiento]"value="33" class="Available"></td>
                    <td><input type="button" name"recibo[asiento]" value="34" id="" class="Available"></td>
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td><input type="submit" name="recibo[asiento]"value="27" id="" class="Available">
                    </td>
                    <td>
                      <input type="submit" name="recibo[asiento]"value="28" id="" class="Available">
                    </td>
                  </tr>
                  <tr>
                    <td><input type="submit" name="recibo[asiento]" value="37" id="" class="Available"></td>
                    <td><input type="submit" name="recibo[asiento]" value="38" id="" class="Available" />
                    </td>
                    <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td><input type="submit" name="ctl00$content$GridMapa$ctl11$Button3" value="31" id="" class="Available" />
                    </td>
                    <td><input type="submit" name="ctl00$content$GridMapa$ctl11$Button4" value="32" id="content_GridMapa_Button4_9" class="Available"></td>
                  </tr>
                  <tr>
                    <td><input type="submit" name="ctl00$content$GridMapa$ctl12$Button1" value="41" id="content_GridMapa_Button1_10" class="Available" ></td>
                    <td> <input type="submit" name="ctl00$content$GridMapa$ctl12$Button2" value="42" id="content_GridMapa_Button2_10" class="Available" /> </td>
                  <td class="Pasillo">_</td><td class="Pasillo">_</td>
                    <td> <input type="submit" name="ctl00$content$GridMapa$ctl12$Button3" value="35" id="" class="Available" /></td>
                    <td> <input type="submit" name="ctl00$content$GridMapa$ctl12$Button4" value="36" id="" class="Available" /></td> </tr>
                  <tr>
				
                                <td>

                                  <input type="submit" name="ctl00$content$GridMapa$ctl13$Button1" value="43" id="content_GridMapa_Button1_11" class="Available" />
                                                            
                                </td><td>
                                                              
                                <input type="submit" name="ctl00$content$GridMapa$ctl13$Button2" value="44" id="content_GridMapa_Button2_11" class="Available" />
                                                           
                                </td><td class="Pasillo">_</td><td class="Pasillo">_</td><td>
                                                            
                                <input type="submit" name="ctl00$content$GridMapa$ctl13$Button3" value="39" id="content_GridMapa_Button3_11" class="Available" />
                                                         
                                </td><td>
                                                                
                                <input type="submit" name="ctl00$content$GridMapa$ctl13$Button4" value="40" id="content_GridMapa_Button4_11" class="Available" />
                                                              
                                </td><tr>
                                 
                                <td>
                                                               
                                  <input type="submit" name="ctl00$content$GridMapa$ctl13$Button1" value="47" id="content_GridMapa_Button1_11" class="Available" />
                                                             
                                </td><td>
                                                            
                                <input type="submit" name="ctl00$content$GridMapa$ctl13$Button2" value="48" id="content_GridMapa_Button2_11" class="Available" />
                                                         
                                </td><td class="Pasillo">_</td><td class="Pasillo">_</td><td>
                                                               
                                <input type="submit" name="ctl00$content$GridMapa$ctl13$Button3" value="45" id="content_GridMapa_Button3_11" class="Available" />
                                                            
                                </td><td>
                                                            
                                <input type="submit" name="ctl00$content$GridMapa$ctl13$Button4" value="46" id="content_GridMapa_Button4_11" class="Available" />
                                                             </td>
                                </tr>
	</table>
	</div>
                                                
</div>
        