config/routes.rb
Discovery::Application.routes.draw do
  
  devise_for :empleados
  resources :paquete
  resources :horarios
  resources :recibo
  resources :terminal
  resources :ruta
  resources :cliente
  resources :verrecibos
  resources :verempleados
  resources :verclientes
  
  get 'verclientes/index'
  get 'verrecibos/index'
  get 'verempleados/index'
  get 'cliente/index'
  get 'ruta/index'
  get 'terminal/index'
  get 'main/index'
  get 'horarios/index'
  get 'paquete/index'
  get 'recibo/index'
  root 'main#index'
  

end

app/models/bus.rb
class Bus < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :empleado  
  has_many :caminos
 def validate
     unless Empleado.find_by_id(empleado_id)
       errors.add(:empleado_id, 'does not exist')
     end
   end # validate
    
    
end

app/models/camino.rb
class Camino < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :terminal
  belongs_to :bus
  has_many :recibos
  
 def validate
     unless Terminal.find_by_id(terminal_id_origen)
       errors.add(:terminal_id_origen, 'does not exist')
     end
     unless Terminal.find_by_id(terminal_id_destino)
       errors.add(:terminal_id_destino, 'does not exist')
     end
   end # validate
  
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :recibos
  has_many :paquetes
  

 
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  belongs_to :terminal
  has_one :bus
  has_many :recibos
  
  def validate
     unless Terminal.find_by_id(terminal_id)
       errors.add(:terminal_id, 'does not exist')
     end
   end
  
  
end

    
      

app/models/paquete.rb
class Paquete < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :recibo
  belongs_to :cliente
  def validate
     unless Recibo.find_by_id(recibo_id)
       errors.add(:recibo_id, 'does not exist')
     end
   end

end

app/models/recibo.rb
class Recibo < ActiveRecord::Base
  belongs_to :empleado
  belongs_to :cliente
  has_one :paquete
  has_one :camino

  validates :fecha_de_viaje, presence: true
 
end

app/models/ruta.rb
class Ruta < ActiveRecord::Base
  belongs_to :terminal
  belongs_to :bus
  has_one :recibo
end

app/models/terminal.rb
class Terminal < ActiveRecord::Base
   has_many :empleados
   has_many :caminos
end

app/controllers/addempleados_controller.rb
class AddempleadosController < ApplicationController
  def index
    @empleados = Empleado.new
  end

  def new
    @terminals = Terminal.all
    @empleado = Empleado.new
  end
    
  def create
    @empleado =Empleado.create(empleado_params)
   if @terminal.save
     redirect_to :controller=>'addempleados'
   else
   end
  end
  
  private
  def empleado_params
     params.require(:terminal).permit(:email, :encrypted_password, :primer_nombre, :segundo_nombre, 
       :primer_apellido, :segundo_apellido, :terminal_id, :sexo, :primer_apellido, :segundo_apellido, 
       :fecha_nacimiento, :fecha_inicio, :direccion, :profesion, :telefono, :nacionalidad, :administrador)
 end
end
  

app/helpers/addempleados_helper.rb
module AddempleadosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  
  def is_active?(link_path)
  if current_page?(link_path)
    "active"
  else
    ""
  end
 end
  
  
  
  
end

app/helpers/cliente_helper.rb
module ClienteHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/paquete_helper.rb
module PaqueteHelper
end

app/helpers/recibo_helper.rb
module ReciboHelper
  
  
  def is_Available?
    
    Recibo.all.each do |t|
     
      if t.asiento?(1)
        "Available"
      else
        "NotAvailable"
      end
    end
    
  end
  
end

app/helpers/ruta_helper.rb
module RutaHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/terminal_helper.rb
module TerminalHelper
end

app/helpers/verclientes_helper.rb
module VerclientesHelper
end

app/helpers/verrecibos_helper.rb
module VerrecibosHelper
end

app/views/addempleados/new.html.erb
<body>

    <div class="navbar-wrapper">
      <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
      <div class="container">

        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
                 <!-- The drop down menu -->
            <ul class="nav pull-right">
              <li class="divider-vertical"></li>
              <li class="dropdown">
                <% if empleado_signed_in? %>              
                <a class="dropdown-toggle" href="#" data-toggle="dropdown"><%= current_empleado.email %> <strong class="caret"></strong> </a>
                <ul class="dropdown-menu">              
                  <% if Empleado.find_by_email(current_empleado.email).administrador? %> 
                   <li> <%= link_to 'Agregar Empleados', new_addempleado_path  %></li>          
                    <li> <%= link_to 'Agregar Rutas', new_rutum_path  %></li> 
                    <li> <%= link_to 'Agregar Terminal', new_terminal_path %></li> 
                  <% end %>
                  <li class="divider"></li>
                  <li> <%= link_to 'Sign out', destroy_empleado_session_path, :method => :delete %>   </li>
                 </ul>                              
                <% else %>
                  <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
                  <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">               
                <!-- <%= link_to 'Sign up', new_empleado_registration_path %> --> or 
                  <form accept-charset="UTF-8" action="/empleados/sign_in" class="new_empleado" id="new_empleado" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" />
                    <input name="authenticity_token" type="hidden" value="pLb2Tof7yQ8/ha0TIEmUdB5r2oUuyCwpnu8BwYlgA2Q=" /></div>
                   <input autofocus="autofocus" id="empleado_email" name="empleado[email]" type="email" value="" style="margin-bottom: 15px; color: black;" size="30" placeholder="email del empleado" />        
                   <input id="empleado_password" name="empleado[password]" type="password" style="margin-bottom: 15px; color: black;" size="30"  placeholder="contraseña" />
                   <input name="empleado[remember_me]" type="hidden" value="0" />
                    <input id="empleado_remember_me" name="empleado[remember_me]" style="float: left; margin-right: 10px;" type="checkbox" value="1" /> 
                   <label for="empleado_remember_me" style="color: black" >Recordame</label>
                   <input class="btn btn-primary"  style="clear: left; width: 100%; height: 32px; font-size: 13px;"  name="commit" type="submit" value="Sign in"/>
                  </form>  
                       </div>
                <% end %>  
                  
              </li>
            </ul>
            <a class="brand" href="#">Transporte Discovery</a>
            <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li><%= link_to 'Inicio', root_path %></li>
                <li><%= link_to 'Horarios', horarios_path %></li>   
                <li><%= link_to 'E-Ticket!', recibo_index_path %></li>   
                <li><a href="javascript:void(0)" onclick="saludo()">Contacto</a></li>                  
              </ul>
            </div><!--/.nav-collapse -->
          </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->
      </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->
  
    <div class="container marketing">
      <!-- Three columns of text below the carousel -->
      <div class="row">
        
        <div class="span4">           
          </div>
        
         <div class="span4">  
          <br>
           <h2>Agregar Empleado</h2>
          <br>
            <%= form_for @empleado, :url => { :action => "create" } do |t| %>
           <p>
            <%= t.label :'email' %>
            <%= t.text_field :email %><br />
           </p>
             <p>
            <%= t.label :'Contraseña' %>
            <%= t.password_field  :encrypted_password %><br />
           </p>
           <p>
            <%= t.label :'primer_nombre' %>
            <%= t.text_field :primer_nombre %><br />
           </p>
           <p>
            <%= t.label :'segundo_nombre' %>
            <%= t.text_field :segundo_nombre %><br />
           </p>
           <p>
            <%= t.label :'primer_apellido' %>
            <%= t.text_field :primer_apellido %><br />
           </p>
             <p>
            <%= t.label :'segundo_apellido' %>
            <%= t.text_field :segundo_apellido %><br />
           </p>
             <p>
            <%= t.label :'direccion' %>
            <%= t.text_area :direccion %><br />
           </p>
            <p>
            <%= t.label :'telefono' %>
            <%= t.text_field :telefono %><br />
           </p>
            <p>
            <%= t.label :'profesion' %>
            <%= t.text_field :profesion %><br />
           </p>
           <p>
             <%= t.label :'genero' %>
             <%= t.select :'sexo', {"Masculino" => 'M', "Femenino" => 'F'}%> 
             <br /> 
           </p>
           <p>
              <%= t.label :'fecha_de_Nacimiento' %>
             <%= t.date_select :'fecha_nacimiento', :start_year => 1950 %>        
           </p>
           <p>
             <%= t.label :'fecha_de_Inicio' %>
             <%= t.date_select :'fecha_inicio', :start_year => 1950 %>           
           </p>
           <p>
             <%= t.label :'nacionalidad' %>
             <%= t.select :'nacionalidad', options_for_select([ "Afganistán", "Albania", "Alemania",
               "Andorra", "Angola", "Anguilla" , "Antártida", "Antigua", "Antillas Holandesas", "Arabia Saudí", "Argelia", "Argentina", "Armenia",
               "Aruba", "Australia", "Austria" , "Azerbaiyán", "Bahamas", "Bahrein", "Bangladesh", "Barbados", "Bélgica", "Belice" , 
               "Benin", "Bermudas", "Bielorrusia" , "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botswana", "Brasil", "Brunei", "Bulgaria",
               "Burkina Faso", "Burundi", "Bután" , "Cabo Verde", "Camboya", "Camerún", "Canadá", "Chad", "Chile", "China",
               "Chipre", "Colombia", "Comores" , "Congo", "Corea", "Corea del Norte", "Costa de Marfíl", "Costa Rica", "Croacia (Hrvatska)", "Cuba",  
               "Dinamarca", "Djibouti", "Dominica" , "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovenia", "España",
               "Estados Unidos", "Estonia", "Etiopía" , "Filipinas", "Finlandia", "Francia", "Gabón", "Gambia", "Georgia", "Ghana",
               "Gibraltar", "Granada", "Grecia" , "Groenlandia", "Guadalupe", "Guam", "Guatemala", "Guayana", "Guinea", "Haití",
               "Hungría", "Honduras", "India", "Indonesia" , "Irak", "Irán", "Irlanda", "Isla Bouvet", "Islandia", "Islas Caimán", "Islas Caimán",
               "Israel", "Italia", "Jamaica" , "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguizistán", "Kiribati", "Kuwait",
               "Lesotho", "Letonia", "Líbano" , "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Madagascar", "Macedonia",
               "Malasia", "Malawi", "Maldivas" , "Malí", "Malta", "Marruecos", "Martinica", "Mauricio", "Mauritania", "Mayotte",
               "México", "Micronesia", "Moldavia" , "Mónaco", "Mongolia", "Montserrat", "Mozambique", "Namibia", "Nauru", "Nepal",
               "Nicaragua", "Níger", "Nigeria" , "Niue", "Norfolk", "Noruega", "Nueva Caledonia", "Nueva Zelanda", "Omán", "Países Bajos",
               "Panamá", "Papúa Nueva Guinea", "Paquistán" , "Paraguay", "Perú", "Pitcairn", "Polinesia Francesa", "Polonia", "Portugal", "Puerto Rico",
               "Reino Unido", "República Centroafricana", "República Checa" , "República de Sudáfrica", "República Dominicana", "República Eslovaca", "Reunión", "Ruanda", "Rumania", "Kuwait",
               "Rusia", "Sahara Occidental", "Saint Kitts y Nevis" , "Samoa", "Samoa Americana", "San Marino", "Senegal", "Seychelles", "Sierra Leona", "Singapur",
               "Siria", "Somalia", "Suazilandia" , "Sudán", "Suiza", "Surinam", "Tailandia", "Taiwán", "Tanzania", "Tayikistán", 
               "Trinidad y Tobago", "Túnez", "Turkmenistán" , "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu",
               "Venezuela", "Vietnam", "Yemen" , "Yugoslavia", "Zambia", "Zimbabue"], "Honduras") %>
           </p>
             <p>
             <%= t.label :'terminal_id' %>   
               <% @terminals.each do |k| %>
               <%= t.select :'terminal_id', {k.nombre => k.id} %>
               <% end %>               
             <br /> 
           </p>
             <p>
             <%= t.label :'administrador' %>
              <%= t.select :'administrador', {"Si" => true, "No" => false}%> 
           </p>

           <p>
             <%= t.submit "Agregar" %>
           </p>
           <% end %>        
          </div>      
      </div>
  </div>
</body>